### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by jLynx** [iP1SMS/disposable-phone-numbers#11]
Here are a few I have found that are not in your list:

- temporary-phone-number.com
- receive-sms-online.cc
- receive-sms-free.cc
- smscodeonline.com
- receivesmss.net
- yunjiema.net
- freereceivesms.com

**Comment by Wikxen** [comment]
You are open to make a PR adding those to the list

**Comment by Thorfrill** [comment]
I will add them to our list. Thanks for the help.
