### ISSUE TITLE
Add other website that offers disposable email service 

### ISSUE THREAD

**Issue by Daniel3356** [iP1SMS/disposable-phone-numbers#15]
more that aren't in the lists

7sim.org
hash4tag.com
freebulksmsonline.com
https://www.proovl.com/test

**Comment by Wikxen** [comment]
Feel free to make a PR

**Comment by Daniel3356** [comment]
What do you mean by PR?

**Comment by Wikxen** [comment]
> What do you mean by PR?

Pull request, but nevermind, I made my own with your suggestions
