### ISSUE TITLE
How to check google voice number?

### ISSUE THREAD

**Issue by wanyy15083** [iP1SMS/disposable-phone-numbers#17]
How to check google voice number?

**Comment by Wikxen** [comment]
Could you elaborate?
We have a JavaScript implementation of this on NPM (https://www.npmjs.com/package/@ip1sms/is-disposable-phone-number)

**Comment by wanyy15083** [comment]
> Could you elaborate? We have a JavaScript implementation of this on NPM (https://www.npmjs.com/package/@ip1sms/is-disposable-phone-number)

Yes, I see. The package contains the some number list. But I want to check the google voice number  or like the disposable  service,   I want to know if you have a solution?  Furthermore, I want to code the common service,instead of
 the number list..But I have no idea.

**Comment by Wikxen** [comment]
> > Could you elaborate? We have a JavaScript implementation of this on NPM (https://www.npmjs.com/package/@ip1sms/is-disposable-phone-number)
> 
> Yes, I see. The package contains the some number list. But I want to check the google voice number or like the disposable service, I want to know if you have a solution? Furthermore, I want to code the common service,instead of the number list..But I have no idea.

This package is aggregating a list scraped from known sites providing disposable phone numbers. Updated almost daily. As long as you keep this package updated the list would contain all of our discovered disposable phone numbers.

Google voice numbers aren't really disposable since they are paid numbers for people to use exclusively. That would be out-of-scope for this project. There may be a Google provided service to query if a number is a Google voice number, if that's what you are after.

**Comment by wanyy15083** [comment]
thank

> > > Could you elaborate? We have a JavaScript implementation of this on NPM (https://www.npmjs.com/package/@ip1sms/is-disposable-phone-number)
> > 
> > 
> > Yes, I see. The package contains the some number list. But I want to check the google voice number or like the disposable service, I want to know if you have a solution? Furthermore, I want to code the common service,instead of the number list..But I have no idea.
> 
> This package is aggregating a list scraped from known sites providing disposable phone numbers. Updated almost daily. As long as you keep this package updated the list would contain all of our discovered disposable phone numbers.
> 
> Google voice numbers aren't really disposable since they are paid numbers for people to use exclusively. That would be out-of-scope for this project. There may be a Google provided service to query if a number is a Google voice number, if that's what you are after.

Than you! I will find some service.
