### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by jesobreira** [iP1SMS/disposable-phone-numbers#2]
Any plans to make this a npm package?

**Comment by Wikxen** [comment]
That's a great idea, I'll talk to the team.

**Comment by jesobreira** [comment]
If you don't mind, I've published a package in npm containing a function that wraps this list: https://www.npmjs.com/package/is-disposable-phonenumber

However since this list is only in GitHub, I have a manual task of updating the package every time the list gets updated. If this list gets published on npm (just like [disposable-domain-names](https://www.npmjs.com/package/disposable-email-domains)), then the update could be automatic just by requiring the package (as done by [is-disposable-email](https://www.npmjs.com/package/is-disposable-email)).

I hope your team appreciates this idea.

**Comment by Wikxen** [comment]
> If you don't mind, I've published a package in npm containing a function that wraps this list: https://www.npmjs.com/package/is-disposable-phonenumber
> 
> However since this list is only in GitHub, I have a manual task of updating the package every time the list gets updated. If this list gets published on npm (just like [disposable-domain-names](https://www.npmjs.com/package/disposable-email-domains)), then the update could be automatic just by requiring the package (as done by [is-disposable-email](https://www.npmjs.com/package/is-disposable-email)).
> 
> I hope your team appreciates this idea.

We now have an is disposable package as well:
https://www.npmjs.com/package/@ip1sms/is-disposable-phone-number
