### ISSUE TITLE
How to add numbers into sms24.me

### ISSUE THREAD

**Issue by othman-atlas** [iP1SMS/disposable-phone-numbers#9]
Hi Team,
Atlas that I represent is a telecom operator able to supply you numbers in several EU countries such as France, NL, UK, Sweden, ...
how can we upload them into your system?

contact: othman@atlascommunications.co

**Comment by Wikxen** [comment]
We are not affiliated with sms24.me. And this project aims to provide people a list of disposable phone numbers for spam protection reasons.

**Comment by othman-atlas** [comment]
we could help people by providing disposable phone numbers, for privacy and protection reasons. 
let me know if you're interested in this project.

**Comment by Wikxen** [comment]
Sounds like the opposite of what this project is about. But my employer may be interested. Send an email to info@ip1.se

**Comment by othman-atlas** [comment]
I've tried to reach you out but in vain. could you pass the info and ask your employer to contact me by email? 
othman@atlascommunications.co 
Thank you!
